# Generated by Django 4.2.17 on 2025-01-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="ID платежной сессии в Stripe",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
    ]
