services:
  db:
    image: postgres:16
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready -u $POSTGRES_USER" ]
      interval: 10s
      retries: 5
      timeout: 5s

  pudemy:
    build: .
    tty: true
    command: >
      bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000" \
      bash -c "celery -A pudemy beat --loglevel=info" \
      bash -c "celery -A pudemy.celery  worker --loglevel=INFO -B"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    env_file:
      - .env

volumes:
  pg_data:
  redis_data:
  static_volume:
