services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  pudemy:
    build: .
    tty: true
    command: >
      bash -c "python3 manage.py collectstatic --noinput \
      && python3 manage.py migrate \
      && gunicorn pudemy.wsgi:application --bind 0.0.0.0:8000"

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    env_file:
      - .env

  pudemy_celery:
    build: .
    command: >
      bash -c "celery -A pudemy worker -l INFO"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  pudemy_celery_beat:
    build: .
    env_file:
      - .env
    command: >
      bash -c "celery -A pudemy beat -l INFO"
    depends_on:
      - redis
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - pudemy

volumes:
  pg_data:
  redis_data:
  static_volume:
  media_volume:
