# Generated by Django 4.2.17 on 2025-01-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_coursesubscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("title",),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="coursesubscription",
            options={
                "ordering": ("course", "user"),
                "verbose_name": "Подписка на курс",
                "verbose_name_plural": "Подписки на курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("title",),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
