# Generated by Django 4.2.17 on 2025-01-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_course_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/previews/",
                verbose_name="Превью",
            ),
        ),
    ]
