# Generated by Django 4.2.17 on 2025-01-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_course_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lessons/previews/",
                verbose_name="Превью",
            ),
        ),
    ]
