# Generated by Django 4.2.17 on 2025-01-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление"
            ),
        ),
    ]
